// <auto-generated />
namespace Net.Pokeshot.JiveSdk.Example.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class jivesdk2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jivesdk2));
        
        string IMigrationMetadata.Id
        {
            get { return "201503091506543_jivesdk2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
